
package org.akigrafsoft.wsdl.helloservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Hello_PortType", targetNamespace = "http://www.examples.com/wsdl/HelloService.wsdl")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface HelloPortType {


    /**
     * 
     * @param firstName
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "greeting", partName = "greeting")
    public String sayHello(
        @WebParam(name = "firstName", partName = "firstName")
        String firstName);

}
