
package org.akigrafsoft.wsdl.helloservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * WSDL File for HelloService
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "Hello_Service", targetNamespace = "http://www.examples.com/wsdl/HelloService.wsdl", wsdlLocation = "file:/home/kmoyse/workspace/WSConnector/ws/HelloService.wsdl")
public class HelloService
    extends Service
{

    private final static URL HELLOSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.akigrafsoft.wsdl.helloservice.HelloService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.akigrafsoft.wsdl.helloservice.HelloService.class.getResource(".");
            url = new URL(baseUrl, "file:/home/kmoyse/workspace/WSConnector/ws/HelloService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/home/kmoyse/workspace/WSConnector/ws/HelloService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        HELLOSERVICE_WSDL_LOCATION = url;
    }

    public HelloService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloService() {
        super(HELLOSERVICE_WSDL_LOCATION, new QName("http://www.examples.com/wsdl/HelloService.wsdl", "Hello_Service"));
    }

    /**
     * 
     * @return
     *     returns HelloPortType
     */
    @WebEndpoint(name = "Hello_Port")
    public HelloPortType getHelloPort() {
        return super.getPort(new QName("http://www.examples.com/wsdl/HelloService.wsdl", "Hello_Port"), HelloPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloPortType
     */
    @WebEndpoint(name = "Hello_Port")
    public HelloPortType getHelloPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.examples.com/wsdl/HelloService.wsdl", "Hello_Port"), HelloPortType.class, features);
    }

}
